name: PR Whisperer AI
description: Generate PR descriptions based on git diff using Python + OpenAI

inputs:
  openai_api_key:
    required: true
    description: OpenAI API key

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run whisperer script
      run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_BASE_REF: ${{ env.GITHUB_BASE_REF }}
