name: PR Whisperer AI

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  whisper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate PR Description
        uses: viniciustakedi/pr-whisperer-ai@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
